apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: mongodb-operator
  namespace: flux-system
spec:
  interval: 5m
  path: "."
  sourceRef:
    kind: GitRepository
    name: devops
    namespace: flux-system
  prune: true
