apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: mongodb-replica-set
  namespace: flux-system
spec:
  interval: 5m
  path: "./kubernetes/mongodb/flux/replica-set/"
  sourceRef:
    kind: GitRepository
    name: devops
    namespace: flux-system
  prune: true
  dependsOn:
  - name: mongodb-operator
