apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 5m
  path: "./kubernetes/metallb/"
  sourceRef:
    kind: GitRepository
    name: devops
    namespace: flux-system
  prune: true
  wait: true
