apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: appsmith
  namespace: flux-system
spec:
  chart:
    spec:
      chart: appsmith
      sourceRef:
        kind: HelmRepository
        name: appsmith
      version: 1.5.1
  install:
    createNamespace: true
    disableWait: false
    remediation:
      retries: -1
  interval: 5m
  releaseName: appsmith
  storageNamespace: appsmith
  targetNamespace: appsmith
  values:
    applicationConfig:
      APPSMITH_MONGODB_URI: "mongodb://admin:Y2hhbmdlbWU%3D@mongodb-0.mongodb-svc.mongodb.svc.cluster.local:27017,mongodb-1.mongodb-svc.mongodb.svc.cluster.local:27017,mongodb-2.mongodb-svc.mongodb.svc.cluster.local:27017/main?ssl=false"
      APPSMITH_REDIS_URL: "redis-master.redis.svc.cluster.local"

