#------------------------------------------------------------------------------
#                           Nginx Ingress Controller
#------------------------------------------------------------------------------
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 1h
  url: https://kubernetes.github.io/ingress-nginx

#------------------------------------------------------------------------------
#                                  Mongodb
#------------------------------------------------------------------------------
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: mongodb
  namespace: flux-system
spec:
  interval: 1h
  url: https://mongodb.github.io/helm-charts

#------------------------------------------------------------------------------
#                                  Bitnami
#------------------------------------------------------------------------------
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.bitnami.com/bitnami

#------------------------------------------------------------------------------
#                                 Autoscaler
#------------------------------------------------------------------------------
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: autoscaler
  namespace: flux-system
spec:
  interval: 1h
  url: https://kubernetes.github.io/autoscaler

#------------------------------------------------------------------------------
#                                  Jetstack
#------------------------------------------------------------------------------
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.jetstack.io

#------------------------------------------------------------------------------
#                                  Velero
#------------------------------------------------------------------------------
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: velero
  namespace: flux-system
spec:
  interval: 1h
  url: https://vmware-tanzu.github.io/helm-charts
