apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

# mongodb-operator
- ../../mongodb/flux/operator/flux-kustomization.yaml
# mongodb-replica-set
- ../../mongodb/flux/replica-set/flux-kustomization.yaml
