apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Helm Repositories
  - helmrepository.yaml

  # appsmith
  - ../../appsmith/flux/flux-kustomization.yaml
  # mongodb-operator
  - ../../mongodb/flux/operator/flux-kustomization.yaml
  # mongodb-replica-set
  - ../../mongodb/flux/replica-set/flux-kustomization.yaml
  # redis
  - ../../redis/flux/flux-kustomization.yaml
