apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq-operator
  namespace: flux-system
spec:
  releaseName: rabbitmq-cluster-operator
  targetNamespace: rabbitmq-system
  storageNamespace: rabbitmq-system
  chart:
    spec:
      chart: rabbitmq-cluster-operator
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 2.3.4
  dependsOn: []
  install:
    createNamespace: true
    disableWait: true
    remediation:
      retries: -1
  interval: 1m
  values: {}
